name: tests
on: [ push, pull_request ]

permissions:
  checks: write
  pull-requests: write

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.5.1"
      - name: Set up Python
        run: uv python install 3.11
      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Run tests
        run: uv run pytest
